runtime: python312

instance_class: F2

entrypoint: python app_new.py

env_variables:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  PORT: "8080"

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65
